insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (1,'Kevin', 'Romero', 'title', 2245643, 'testemail@2email.com', '2020-05-01', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (2,'Moe', 'Aydin', 'title', 2245643, 'testemail@2email.com', '2020-05-01', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (3, 'Eveleen', 'Romanini', 'Junior Executive', 3195618, 'eromanini2@about.me', '2020-01-05', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (4, 'Dallis', 'Bottinelli', 'Electrical Engineer', 3193473, 'dbottinelli3@parallels.com', '2019-10-06', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (5, 'Tabor', 'Rosensaft', 'Registered Nurse', 3722997, 'trosensaft4@multiply.com', '2019-11-17', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (6, 'Foss', 'Camel', 'Database Administrator II', 3600999, 'fcamel5@examiner.com', '2020-03-20', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (7, 'Kerry', 'Sutherland', 'Assistant Media Planner', 3572530, 'ksutherland6@twitter.com', '2019-07-13', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (8, 'Natal', 'Nightingale', 'Recruiter', 3255479, 'nnightingale7@ucoz.ru', '2019-06-03', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (9, 'Cirstoforo', 'Twiddle', 'Account Coordinator', 3735883, 'ctwiddle8@tinypic.com', '2020-03-09', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (10, 'Tanhya', 'Gilliver', 'Civil Engineer', 3968270, 'tgilliver9@eventbrite.com', '2019-05-05', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (11, 'Ara', 'Musterd', 'Recruiter', 3897584, 'amusterda@youtu.be', '2019-04-27', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (12, 'Allan', 'Skirving', 'Senior Editor', 3499578, 'askirvingb@shareasale.com', '2019-04-02', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (13, 'Richart', 'McLeman', 'Quality Control Specialist', 3900486, 'rmclemanc@hhs.gov', '2019-11-17', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (14, 'Aleen', 'Domerq', 'Sales Associate', 3135790, 'adomerqd@a8.net', '2019-06-21', 3);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (15, 'Jeddy', 'Trudgeon', 'Account Coordinator', 3227556, 'jtrudgeone@rediff.com', '2020-02-28', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (16, 'Melisandra', 'Klink', 'Database Administrator III', 3027238, 'mklinkf@stumbleupon.com', '2019-04-21', 2);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (17, 'Marinna', 'Alderson', 'Account Coordinator', 3981711, 'maldersong@epa.gov', '2019-07-24', 2);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (18, 'Winn', 'Pabelik', 'Senior Editor', 3674471, 'wpabelikh@barnesandnoble.com', '2019-11-14', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (19, 'Maurene', 'Philips', 'Food Chemist', 3684597, 'mphilipsi@imdb.com', '2019-07-05', 1);
insert into employee (id, first_name, last_name, title, phone_number, email, hire_date, dept_number) values (20, 'Ozzy', 'Marusyak', 'Accounting Assistant III', 3695211, 'omarusyakj@weibo.com', '2019-12-06', 1);

insert into department(dept_number, dept_name, manager_Id) values(1, 'Sales', null);
insert into department(dept_number, dept_name, manager_Id) values(2, 'Engineering', null);
insert into department(dept_number, dept_name, manager_Id) values(3, 'Marketing', null);