DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR2(255) NOT NULL DEFAULT '',
    LAST_NAME VARCHAR2(255) NOT NULL DEFAULT '',
    TITLE VARCHAR2(255) NOT NULL DEFAULT '',
    PHONE_NUMBER VARCHAR2(255) NOT NULL DEFAULT '',
    EMAIL VARCHAR2(255) NOT NULL DEFAULT '',
    HIRE_DATE VARCHAR2(255) NOT NULL DEFAULT '',
    MANAGER_ID INT NOT NULL DEFAULT '',
    DEPT_NUMBER INT NOT NULL DEFAULT '',
    PRIMARY KEY (ID)
);

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPT_NUMBER NUMBER(10,0) NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR2(255) NOT NULL DEFAULT '',
    MANAGER_ID VARCHAR2(255) NOT NULL DEFAULT '',
    PRIMARY KEY (DEPT_NUMBER)
);

DROP TABLE PERSON;

CREATE TABLE PERSON (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR2(255) NOT NULL DEFAULT '',
  LAST_NAME VARCHAR2(255) NOT NULL DEFAULT '',
  MOBILE VARCHAR2(20) NOT NULL DEFAULT '',
  BIRTHDAY DATE DEFAULT NULL,
  PRIMARY KEY (ID));

DROP TABLE HOME;

CREATE TABLE HOME (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  ADDRESS VARCHAR2(255) not null default '',
  HOMENUMBER varchar2(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
);


DROP TABLE CAR;

CREATE TABLE CAR (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  MAKE VARCHAR2(255) not null default '',
  MODEL varchar2(255) NOT NULL DEFAULT '',
  YEAR VARCHAR2(5) NOT NULL DEFAULT '01907',
  PRIMARY KEY (ID)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;